"""create change requests and config backups

Revision ID: 32f5e4e66ee3
Revises: 93836ef06000
Create Date: 2026-07-27 16:43:07.900353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f5e4e66ee3'
down_revision = '93836ef06000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('change_request_id', sa.Integer(), nullable=True),
    sa.Column('running_config', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_backups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_backups_change_request_id'), ['change_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_backups_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_backups_device_id'), ['device_id'], unique=False)

    op.create_table('change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('commands', sa.JSON(), nullable=False),
    sa.Column('verification_commands', sa.JSON(), nullable=False),
    sa.Column('rollback_commands', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('apply_output', sa.Text(), nullable=True),
    sa.Column('verification_output', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('backup_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['backup_id'], ['config_backups.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_requests_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_requests_requested_by_id'), ['requested_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_requests_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_change_requests_device_id'))
        batch_op.drop_index(batch_op.f('ix_change_requests_created_at'))

    op.drop_table('change_requests')
    with op.batch_alter_table('config_backups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_backups_device_id'))
        batch_op.drop_index(batch_op.f('ix_config_backups_created_at'))
        batch_op.drop_index(batch_op.f('ix_config_backups_change_request_id'))

    op.drop_table('config_backups')
    # ### end Alembic commands ###
