"""create device credentials

Revision ID: 4ad75a5c1235
Revises: 9d3457562b41
Create Date: 2026-07-27 16:12:34.539793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad75a5c1235'
down_revision = '9d3457562b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('enable_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_credentials_device_id'), ['device_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_credentials_device_id'))

    op.drop_table('device_credentials')
    # ### end Alembic commands ###
