"""create device snapshots

Revision ID: 93836ef06000
Revises: d3b4fc60b0ce
Create Date: 2026-07-27 16:38:54.428987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93836ef06000'
down_revision = 'd3b4fc60b0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('raw_output', sa.JSON(), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_snapshots_device_id'), ['device_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_snapshots_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_snapshots_created_at'))

    op.drop_table('device_snapshots')
    # ### end Alembic commands ###
