"""add requires_confirmation to change requests

Revision ID: b2ace2e71682
Revises: 4a341c72d60c
Create Date: 2026-07-31 20:27:47.984531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ace2e71682'
down_revision = '4a341c72d60c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_confirmation', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.drop_column('requires_confirmation')

    # ### end Alembic commands ###
