"""create command executions

Revision ID: d3b4fc60b0ce
Revises: 4ad75a5c1235
Create Date: 2026-07-27 16:33:21.031228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b4fc60b0ce'
down_revision = '4ad75a5c1235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('command', sa.String(length=512), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('command_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_command_executions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_command_executions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_command_executions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_command_executions_user_id'))
        batch_op.drop_index(batch_op.f('ix_command_executions_device_id'))
        batch_op.drop_index(batch_op.f('ix_command_executions_created_at'))

    op.drop_table('command_executions')
    # ### end Alembic commands ###
